[defaults]
identity_file = "~/.ssh/id_rsa"

[servers.devbox]
host = "10.92.1.163"
port = 22
user = "root"

[servers.ops]
host = "foo-10-92-1-163"
user = "ops"
identity_file = "~/.ssh/id_ed25519"

[servers.db]
host = "10.92.1.200"
user = "dba"
password = "REPLACE_ME"
